spring:
  jpa:
    database: POSTGRESQL
    show:
    sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
  datasource:
    username: csnacfps
    password: iZR7YSw6hYb5i3u_T0h_n0LLdL0udAhL
    url: jdbc:postgresql:postgres://csnacfps:iZR7YSw6hYb5i3u_T0h_n0LLdL0udAhL@salt.db.elephantsql.com/csnacfps